From ros:humble


RUN apt-get update && \
    sudo apt install && \ 
    ros-humble-nav-msgs -y && \
    ros-humble-geometry-msgs -y && \
    ros-humble-sensor-msgs -y && \
    apt install ros-humble-rviz2 -y && \
    sudo apt install ros-humble-vision-opencv -y && \
    apt install ros-humble-cv-bridge -y  && \
    apt install ros-humble-navigation2 -y  && \
    apt install ros-humble-nav2-bringup


RUN apt install python3-pip -y
RUN apt install ros-humble-tf-transformations -y
